import { chromium } from 'playwright-core';
import { pathToFileURL } from 'node:url';
import { join } from 'node:path';
const exe = process.env.CHROMIUM_PATH || '/opt/pw-browsers/chromium';
const url = pathToFileURL(join(process.cwd(), 'dist', 'world.html')).href;
const browser = await chromium.launch({ executablePath: exe, args: ['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--ignore-gpu-blocklist','--enable-unsafe-swiftshader'] });
const page = await browser.newPage({ viewport: { width: 1280, height: 760 } });
const errors=[]; page.on('console',m=>{if(m.type()==='error')errors.push(m.text())}); page.on('pageerror',e=>errors.push('PE:'+e.message));
await page.goto(url,{waitUntil:'load'}); await page.waitForTimeout(800);
const start = await page.evaluate(()=>({money:document.getElementById('money').textContent, items:Object.keys(window.__dbg.player.items)}));
await page.evaluate(()=>{ window.__dbg.gainMoney(120); window.__dbg.giveItem('snack','Energy bar',3,2); });
await page.keyboard.press('i'); await page.waitForTimeout(200);
await page.screenshot({path:join('dist','money.png')});
const after = await page.evaluate(()=>({money:document.getElementById('money').textContent}));
// reload → persistence
await page.reload({waitUntil:'load'}); await page.waitForTimeout(700);
const reloaded = await page.evaluate(()=>({money:document.getElementById('money').textContent, items:Object.keys(window.__dbg.player.items)}));
await browser.close();
console.log('start:',JSON.stringify(start));
console.log('after +120,+snack:',JSON.stringify(after));
console.log('after reload (persisted):',JSON.stringify(reloaded));
console.log('errors:',errors.length?errors.slice(0,5):'none');
