import { chromium } from 'playwright-core';
import { pathToFileURL } from 'node:url';
import { join } from 'node:path';
const exe = process.env.CHROMIUM_PATH || '/opt/pw-browsers/chromium';
const url = pathToFileURL(join(process.cwd(),'dist','world.html')).href;
const browser = await chromium.launch({ executablePath: exe, args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--ignore-gpu-blocklist','--enable-unsafe-swiftshader'] });
const page = await browser.newPage({ viewport:{width:1280,height:760} });
const errors=[]; page.on('console',m=>{if(m.type()==='error')errors.push(m.text())}); page.on('pageerror',e=>errors.push('PE:'+e.message));
await page.goto(url,{waitUntil:'load'}); await page.waitForTimeout(800);
const found = await page.evaluate(()=>{ window.__dbg.gainMoney(300); return window.__dbg.findHome(); });
await page.waitForTimeout(300);
await page.screenshot({path:join('dist','home-locked.png')});
const beforeRent = await page.evaluate(()=>({home:window.__dbg.home, money:window.__dbg.player.money, mode:window.__dbg.mode}));
await page.evaluate(()=>window.__dbg.rent());
await page.waitForTimeout(300);
const afterRent = await page.evaluate(()=>({home:window.__dbg.home, money:window.__dbg.player.money, mode:window.__dbg.mode}));
await page.screenshot({path:join('dist','home-inside.png')});
await browser.close();
console.log('found residential:',JSON.stringify(found));
console.log('before rent:',JSON.stringify(beforeRent));
console.log('after rent (should be home set, -150, indoors):',JSON.stringify(afterRent));
console.log('errors:',errors.length?errors.slice(0,5):'none');
