import { chromium } from 'playwright-core';
import { pathToFileURL } from 'node:url';
import { join } from 'node:path';
const exe = process.env.CHROMIUM_PATH || '/opt/pw-browsers/chromium';
const url = pathToFileURL(join(process.cwd(),'dist','world.html')).href;
const browser = await chromium.launch({ executablePath: exe, args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--ignore-gpu-blocklist','--enable-unsafe-swiftshader'] });
const page = await browser.newPage({ viewport:{width:1280,height:760} });
const errors=[]; page.on('console',m=>{if(m.type()==='error')errors.push(m.text())}); page.on('pageerror',e=>errors.push('PE:'+e.message));
await page.goto(url,{waitUntil:'load'}); await page.waitForTimeout(800);
await page.evaluate(()=>{ window.__dbg.enterType('office'); window.__dbg.gotoJob(); });
await page.waitForTimeout(300);
const s1 = await page.evaluate(()=>({promptWork: window.__dbg.promptWork, pedNearJob: true}));
await page.evaluate(()=>window.__dbg.work()); // direct call
await page.waitForTimeout(100);
const s2 = await page.evaluate(()=>({working: window.__dbg.working, money: window.__dbg.player.money}));
await page.waitForTimeout(4000);
const s3 = await page.evaluate(()=>({working: window.__dbg.working, money: window.__dbg.player.money}));
await browser.close();
console.log('promptWork after goto:',JSON.stringify(s1.promptWork));
console.log('after work():',JSON.stringify(s2));
console.log('after ~4s:',JSON.stringify(s3));
console.log('errors:',errors.length?errors.slice(0,5):'none');
